source "azure-arm" "autogenerated_1"{
subscription_id = "ec907711-acd7-4191-9983-9577afbe3ce1"
build_resource_group_name = "VM-automate-Syl"
managed_image_resource_group_name = "VM-automate-Syl"
managed_image_name = "gitlab-srv"
os_type= "Linux"
image_publisher = "Canonical"
image_offer = "UbuntuServer"
image_sku = "18.04-LTS"     
use_interactive_auth = true
      
  azure_tags = {
  dept = "Automation",
  task = "installAutomationServer"
  }
      
  vm_size                           = "Standard_DS2_v2"      
}
  

build {
  sources = ["source.azure-arm.autogenerated_1"]

  provisioner "shell" {     
      inline = [
        "sudo apt-get update",
        "sudo apt-get install -y curl openssh-server ca-certificates",
        "curl https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.deb.sh | sudo bash",
        "sudo EXTERNAL_URL=\"http://gitlab.example.com\" apt-get install -y gitlab-ce"
      ]
  }  
}