source "azure-arm" "autogenerated_1"{
subscription_id = "ec907711-acd7-4191-9983-9577afbe3ce1"
build_resource_group_name = "VM-automate-Syl"
managed_image_resource_group_name = "VM-automate-Syl"
managed_image_name = "jenkin-srv"
os_type= "Linux"
image_publisher = "Canonical"
image_offer = "UbuntuServer"
image_sku = "18.04-LTS"     
use_interactive_auth = true
      
  azure_tags = {
  dept = "Automation",
  task = "installAutomationServer"
  }
      
  vm_size                           = "Standard_DS2_v2"      
}
  

build {
  sources = ["source.azure-arm.autogenerated_1"]

  provisioner "shell" {     
      inline = [
        "sudo apt-get update",
        "sudo apt-get install -y default-jre",
        "curl -fsSL https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key | sudo tee /usr/share/keyrings/jenkins-keyring.asc > /dev/null",
        "echo deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/ | sudo tee /etc/apt/sources.list.d/jenkins.list > /dev/null",
        "sudo apt-get update",
        "sudo apt-get install -y jenkins"
      ]
  }  
}